package formatter;

import java.awt.Color;
import java.awt.Font;

/**
 * <code>Messages</code> are logical combinations of a sender, time stamp, and text
 * with font.  They are the small strings of text that you send back and forth in IMs.
 * 
 * @author Andrew Correa
 */
public class Message implements Event
{
	private String sender;     // The SN of the person who sent this message.
	private Timestamp time;    // The time this Message was sent.
	private String message;    // The actual text of the message.
	private Color color;       // The font color of the text of the message.
	private Font font;         // The font of the message.
	private boolean auto;      // true if this was an auto-reply.
	
	/**
	 * Creates a new <code>Message</code>.&nbsp;Assumes black-on-white text.
	 *
	 * @param sender Screen name of the sender.
	 * @param date The time the message was sent.
	 * @param message The text of the message.
	 * @param auto Whether this is an auto-generated message or not.
	 */
	public Message(String sender, Timestamp time, String message, boolean auto)
	{
		this(sender, time, message, Color.BLACK, new Font("arial", Font.PLAIN, 12), auto);
	}
	
	/**
	 * Creates a new <code>Message</code>.
	 *
	 * @param sender Screen name of the sender.
	 * @param date The time the message was sent.
	 * @param message The text of the message.
	 * @param color The color of the text of the message.
	 * @param font The font the message should be in.
	 * @param auto Whether this is an auto-generated message or not.
	 */
	public Message(String sender, Timestamp time, String message, Color color, Font font, boolean auto)
	{
		this.sender = sender;
		this.time = time;
		this.message = message;
		this.color = color;
		this.font = font;
		this.auto = auto;
	}
	
	
	
	////////////////////////////////////////////////////////////////////////////
	// --------------------------- Simple getters --------------------------- //
	////////////////////////////////////////////////////////////////////////////
	
	/**
	 * Gets the screenname of the sender of this message.
	 *
	 * @return The screenname of the sender.
	 */
	public String getSender()
	{
		return sender;
	}
	
	/**
	 * Gets the text of the message sent.
	 *
	 * @return The text of the message.
	 */
	public String getMessage()
	{
		return message; 
	}
	
	/**
	 * Gets the font Color of the message.
	 *
	 * @return The font color of the message.
	 */
	public Color getColor()
	{
		return color; 
	}
	
	/**
	 * Gets the font face of the message.
	 *
	 * @return The font face.
	 */
	public Font getFont()
	{
		return font; 
	}
	
	/**
	 * Gets the Time this message was sent.
	 *
	 * @return The time the message was sent.
	 */
	public Timestamp getTimestamp()
	{
		return time;
	}
	
	/**
	 * Returns <code>true</code> when the <code>Message</code> is auto-generated
	 * and <code>false</code> when it is not.
	 *
	 * @return Whether this is an auto-generated message or not.
	 */
	public boolean isAutoGenerated()
	{
		return auto;
	}

	/**
	 * Appends the text of the {@link String} to the end of this
	 * <code>Message</code> separated by a newline character.
	 *
	 * @param The text to append to the end of this <code>Message</code>.
	 */
	public void append(String msg)
	{
		message += "\n" + msg;
	}
}
